ALTER TABLE mondial_inscriptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE mondial_inscriptions ADD COLUMN IF NOT EXISTS ticket_given_at TIMESTAMPTZ;
